# Generated by Django 5.2 on 2025-04-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(default='', max_length=300)),
                ('image', models.ImageField(upload_to='uploads/products/')),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
